#pragma once

#define USB_SUSPEND_WAKEUP_DELAY 0

#define PERMISSIVE_HOLD

#define HOLD_ON_OTHER_KEYPRESS

#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 400
#undef LEADER_NO_TIMEOUT

#define MK_MOMENTARY_ACCEL
#define MK_C_OFFSET_0 1
#define MK_C_INTERVAL_0 32
#define MK_C_OFFSET_1 4
#define MK_C_INTERVAL_1 16
#define MK_C_OFFSET_2 32
#define MK_C_INTERVAL_2 16
#define MK_W_OFFSET_UNMOD	1
#define MK_W_INTERVAL_UNMOD	40
#define MK_W_OFFSET_0	1	
#define MK_W_INTERVAL_0 360
#define MK_W_OFFSET_1	1
#define MK_W_INTERVAL_1	120
#define MK_W_OFFSET_2	1
#define MK_W_INTERVAL_2 20

#define MIDI_ADVANCED
